[2024-01-25T21:36:59.784-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2024-01-25T10:00:00+00:00/task_id=invoke_lambda_function permission to 509
[2024-01-25T21:36:59.836-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2024-01-25T10:00:00+00:00/task_id=invoke_lambda_function permission to 509
[2024-01-25T21:36:59.856-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2024-01-25T10:00:00+00:00 [queued]>
[2024-01-25T21:36:59.868-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2024-01-25T10:00:00+00:00 [queued]>
[2024-01-25T21:36:59.869-0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-25T21:36:59.907-0300] {taskinstance.py:1382} INFO - Executing <Task(LambdaInvokeFunctionOperator): invoke_lambda_function> on 2024-01-25 10:00:00+00:00
[2024-01-25T21:36:59.908-0300] {standard_task_runner.py:57} INFO - Started process 1468 to run task
[2024-01-25T21:36:59.911-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'how-desafio-03', 'invoke_lambda_function', 'scheduled__2024-01-25T10:00:00+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp7la_yy4v']
[2024-01-25T21:36:59.912-0300] {standard_task_runner.py:85} INFO - Job 184: Subtask invoke_lambda_function
[2024-01-25T21:36:59.970-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2024-01-25T10:00:00+00:00/task_id=invoke_lambda_function permission to 509
[2024-01-25T21:36:59.972-0300] {task_command.py:416} INFO - Running <TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2024-01-25T10:00:00+00:00 [running]> on host 14111-NB.
[2024-01-25T21:37:00.108-0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='how-desafio-03' AIRFLOW_CTX_TASK_ID='invoke_lambda_function' AIRFLOW_CTX_EXECUTION_DATE='2024-01-25T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-25T10:00:00+00:00'
[2024-01-25T21:37:00.110-0300] {lambda_function.py:211} INFO - Invoking AWS Lambda function: teste with payload: {"weather_daily": {"date": "1706229000"}}
[2024-01-25T21:37:00.117-0300] {base.py:73} INFO - Using connection ID 'aws_default' for task execution.
[2024-01-25T21:37:00.118-0300] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-01-25T21:37:04.689-0300] {lambda_function.py:220} INFO - Lambda response metadata: {'RequestId': '23965390-a0b0-454f-b533-a3e0f01953bb', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Fri, 26 Jan 2024 00:37:26 GMT', 'content-type': 'application/json', 'content-length': '114', 'connection': 'keep-alive', 'x-amzn-requestid': '23965390-a0b0-454f-b533-a3e0f01953bb', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-65b2fec2-05acea763fda48b17829cae3;sampled=0;lineage=7d52695d:0'}, 'RetryAttempts': 0}
[2024-01-25T21:37:04.691-0300] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/amazon/aws/operators/lambda_function.py", line 226, in execute
    raise ValueError(
ValueError: ('Lambda function execution resulted in error', {'ResponseMetadata': {'RequestId': '23965390-a0b0-454f-b533-a3e0f01953bb', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Fri, 26 Jan 2024 00:37:26 GMT', 'content-type': 'application/json', 'content-length': '114', 'connection': 'keep-alive', 'x-amzn-requestid': '23965390-a0b0-454f-b533-a3e0f01953bb', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-65b2fec2-05acea763fda48b17829cae3;sampled=0;lineage=7d52695d:0'}, 'RetryAttempts': 0}, 'Payload': '{"errorMessage":"2024-01-26T00:37:26.056Z 23965390-a0b0-454f-b533-a3e0f01953bb Task timed out after 3.01 seconds"}'})
[2024-01-25T21:37:04.703-0300] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=how-desafio-03, task_id=invoke_lambda_function, execution_date=20240125T100000, start_date=20240126T003659, end_date=20240126T003704
[2024-01-25T21:37:04.732-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 184 for task invoke_lambda_function (('Lambda function execution resulted in error', {'ResponseMetadata': {'RequestId': '23965390-a0b0-454f-b533-a3e0f01953bb', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Fri, 26 Jan 2024 00:37:26 GMT', 'content-type': 'application/json', 'content-length': '114', 'connection': 'keep-alive', 'x-amzn-requestid': '23965390-a0b0-454f-b533-a3e0f01953bb', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-65b2fec2-05acea763fda48b17829cae3;sampled=0;lineage=7d52695d:0'}, 'RetryAttempts': 0}, 'Payload': '{"errorMessage":"2024-01-26T00:37:26.056Z 23965390-a0b0-454f-b533-a3e0f01953bb Task timed out after 3.01 seconds"}'}); 1468)
[2024-01-25T21:37:04.755-0300] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-25T21:37:04.787-0300] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
