[2024-02-06T21:33:25.455-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-3/run_id=manual__2024-02-07T00:23:22.077250+00:00/task_id=wait_for_step permission to 509
[2024-02-06T21:33:25.537-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-3/run_id=manual__2024-02-07T00:23:22.077250+00:00/task_id=wait_for_step permission to 509
[2024-02-06T21:33:25.570-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: how-desafio-3.wait_for_step manual__2024-02-07T00:23:22.077250+00:00 [queued]>
[2024-02-06T21:33:25.590-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: how-desafio-3.wait_for_step manual__2024-02-07T00:23:22.077250+00:00 [queued]>
[2024-02-06T21:33:25.592-0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-02-06T21:33:25.642-0300] {taskinstance.py:1382} INFO - Executing <Task(EmrStepSensor): wait_for_step> on 2024-02-07 00:23:22.077250+00:00
[2024-02-06T21:33:25.645-0300] {standard_task_runner.py:57} INFO - Started process 991 to run task
[2024-02-06T21:33:25.648-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'how-desafio-3', 'wait_for_step', 'manual__2024-02-07T00:23:22.077250+00:00', '--job-id', '341', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp5y5hv29b']
[2024-02-06T21:33:25.650-0300] {standard_task_runner.py:85} INFO - Job 341: Subtask wait_for_step
[2024-02-06T21:33:25.820-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-3/run_id=manual__2024-02-07T00:23:22.077250+00:00/task_id=wait_for_step permission to 509
[2024-02-06T21:33:25.825-0300] {task_command.py:416} INFO - Running <TaskInstance: how-desafio-3.wait_for_step manual__2024-02-07T00:23:22.077250+00:00 [running]> on host 14111-NB.
[2024-02-06T21:33:26.140-0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='how-desafio-3' AIRFLOW_CTX_TASK_ID='wait_for_step' AIRFLOW_CTX_EXECUTION_DATE='2024-02-07T00:23:22.077250+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-07T00:23:22.077250+00:00'
[2024-02-06T21:33:26.178-0300] {base.py:73} INFO - Using connection ID 'aws_default' for task execution.
[2024-02-06T21:33:26.180-0300] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-02-06T21:33:26.531-0300] {emr.py:575} INFO - Poking step s-00356731DDJ4R4IXZ7ZL on cluster j-3T1MGLE59GXWM
[2024-02-06T21:33:27.926-0300] {emr.py:79} INFO - Job flow currently PENDING
[2024-02-06T21:34:27.989-0300] {emr.py:575} INFO - Poking step s-00356731DDJ4R4IXZ7ZL on cluster j-3T1MGLE59GXWM
[2024-02-06T21:34:29.569-0300] {emr.py:79} INFO - Job flow currently PENDING
[2024-02-06T21:35:29.634-0300] {emr.py:575} INFO - Poking step s-00356731DDJ4R4IXZ7ZL on cluster j-3T1MGLE59GXWM
[2024-02-06T21:35:31.159-0300] {emr.py:79} INFO - Job flow currently PENDING
[2024-02-06T21:35:40.123-0300] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 991. PIDs of all processes in the group: [991]
[2024-02-06T21:35:40.124-0300] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 991
[2024-02-06T21:35:40.125-0300] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-02-06T21:35:40.158-0300] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/amazon/aws/sensors/emr.py", line 624, in execute
    super().execute(context=context)
  File "/usr/local/lib/python3.10/dist-packages/airflow/sensors/base.py", line 285, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-02-06T21:35:40.164-0300] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=how-desafio-3, task_id=wait_for_step, execution_date=20240207T002322, start_date=20240207T003325, end_date=20240207T003540
[2024-02-06T21:35:40.232-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 341 for task wait_for_step (Task received SIGTERM signal; 991)
[2024-02-06T21:35:40.258-0300] {process_utils.py:79} INFO - Process psutil.Process(pid=991, status='terminated', exitcode=1, started='21:33:24') (991) terminated with exit code 1
