[2023-10-18T20:38:59.943-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2023-10-17T18:10:00+00:00/task_id=invoke_lambda_function permission to 509
[2023-10-18T20:39:00.010-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2023-10-17T18:10:00+00:00/task_id=invoke_lambda_function permission to 509
[2023-10-18T20:39:00.038-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2023-10-17T18:10:00+00:00 [queued]>
[2023-10-18T20:39:00.052-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2023-10-17T18:10:00+00:00 [queued]>
[2023-10-18T20:39:00.052-0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-18T20:39:00.096-0300] {taskinstance.py:1382} INFO - Executing <Task(LambdaInvokeFunctionOperator): invoke_lambda_function> on 2023-10-17 18:10:00+00:00
[2023-10-18T20:39:00.098-0300] {standard_task_runner.py:57} INFO - Started process 156 to run task
[2023-10-18T20:39:00.099-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'how-desafio-03', 'invoke_lambda_function', 'scheduled__2023-10-17T18:10:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpr013b_41']
[2023-10-18T20:39:00.100-0300] {standard_task_runner.py:85} INFO - Job 25: Subtask invoke_lambda_function
[2023-10-18T20:39:00.173-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2023-10-17T18:10:00+00:00/task_id=invoke_lambda_function permission to 509
[2023-10-18T20:39:00.176-0300] {task_command.py:416} INFO - Running <TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2023-10-17T18:10:00+00:00 [running]> on host 14111-NB.
[2023-10-18T20:39:00.300-0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='how-desafio-03' AIRFLOW_CTX_TASK_ID='invoke_lambda_function' AIRFLOW_CTX_EXECUTION_DATE='2023-10-17T18:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-17T18:10:00+00:00'
[2023-10-18T20:39:00.300-0300] {lambda_function.py:211} INFO - Invoking AWS Lambda function: my_first_test with payload: None
[2023-10-18T20:39:00.315-0300] {base.py:73} INFO - Using connection ID 'aws_default' for task execution.
[2023-10-18T20:39:00.316-0300] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2023-10-18T20:39:01.201-0300] {lambda_function.py:220} INFO - Lambda response metadata: {'RequestId': 'be2da1c1-262d-4f53-860c-44b63dab5451', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Wed, 18 Oct 2023 23:39:02 GMT', 'content-type': 'application/json', 'content-length': '234', 'connection': 'keep-alive', 'x-amzn-requestid': 'be2da1c1-262d-4f53-860c-44b63dab5451', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-65306c96-1b985f997bfc671e33eda2c8;sampled=0;lineage=2d7f70ec:0'}, 'RetryAttempts': 0}
[2023-10-18T20:39:01.203-0300] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/amazon/aws/operators/lambda_function.py", line 226, in execute
    raise ValueError(
ValueError: ('Lambda function execution resulted in error', {'ResponseMetadata': {'RequestId': 'be2da1c1-262d-4f53-860c-44b63dab5451', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Wed, 18 Oct 2023 23:39:02 GMT', 'content-type': 'application/json', 'content-length': '234', 'connection': 'keep-alive', 'x-amzn-requestid': 'be2da1c1-262d-4f53-860c-44b63dab5451', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-65306c96-1b985f997bfc671e33eda2c8;sampled=0;lineage=2d7f70ec:0'}, 'RetryAttempts': 0}, 'Payload': '{"errorMessage": "\'key1\'", "errorType": "KeyError", "requestId": "be2da1c1-262d-4f53-860c-44b63dab5451", "stackTrace": ["  File \\"/var/task/lambda_function.py\\", line 8, in lambda_handler\\n    print(\\"value1 = \\" + event[\'key1\'])\\n"]}'})
[2023-10-18T20:39:01.232-0300] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=how-desafio-03, task_id=invoke_lambda_function, execution_date=20231017T181000, start_date=20231018T233900, end_date=20231018T233901
[2023-10-18T20:39:01.270-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 25 for task invoke_lambda_function (('Lambda function execution resulted in error', {'ResponseMetadata': {'RequestId': 'be2da1c1-262d-4f53-860c-44b63dab5451', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Wed, 18 Oct 2023 23:39:02 GMT', 'content-type': 'application/json', 'content-length': '234', 'connection': 'keep-alive', 'x-amzn-requestid': 'be2da1c1-262d-4f53-860c-44b63dab5451', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-65306c96-1b985f997bfc671e33eda2c8;sampled=0;lineage=2d7f70ec:0'}, 'RetryAttempts': 0}, 'Payload': '{"errorMessage": "\'key1\'", "errorType": "KeyError", "requestId": "be2da1c1-262d-4f53-860c-44b63dab5451", "stackTrace": ["  File \\"/var/task/lambda_function.py\\", line 8, in lambda_handler\\n    print(\\"value1 = \\" + event[\'key1\'])\\n"]}'}); 156)
[2023-10-18T20:39:01.278-0300] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-18T20:39:01.307-0300] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
