[2023-10-18T20:42:53.853-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2023-10-18T17:10:00+00:00/task_id=invoke_lambda_function permission to 509
[2023-10-18T20:42:53.936-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2023-10-18T17:10:00+00:00/task_id=invoke_lambda_function permission to 509
[2023-10-18T20:42:53.976-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2023-10-18T17:10:00+00:00 [queued]>
[2023-10-18T20:42:54.009-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2023-10-18T17:10:00+00:00 [queued]>
[2023-10-18T20:42:54.010-0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-18T20:42:54.067-0300] {taskinstance.py:1382} INFO - Executing <Task(LambdaInvokeFunctionOperator): invoke_lambda_function> on 2023-10-18 17:10:00+00:00
[2023-10-18T20:42:54.069-0300] {standard_task_runner.py:57} INFO - Started process 215 to run task
[2023-10-18T20:42:54.071-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'how-desafio-03', 'invoke_lambda_function', 'scheduled__2023-10-18T17:10:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp1wf_g4qt']
[2023-10-18T20:42:54.072-0300] {standard_task_runner.py:85} INFO - Job 50: Subtask invoke_lambda_function
[2023-10-18T20:42:54.173-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2023-10-18T17:10:00+00:00/task_id=invoke_lambda_function permission to 509
[2023-10-18T20:42:54.175-0300] {task_command.py:416} INFO - Running <TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2023-10-18T17:10:00+00:00 [running]> on host 14111-NB.
[2023-10-18T20:42:54.333-0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='how-desafio-03' AIRFLOW_CTX_TASK_ID='invoke_lambda_function' AIRFLOW_CTX_EXECUTION_DATE='2023-10-18T17:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-18T17:10:00+00:00'
[2023-10-18T20:42:54.334-0300] {lambda_function.py:211} INFO - Invoking AWS Lambda function: my_first_test with payload: None
[2023-10-18T20:42:54.352-0300] {base.py:73} INFO - Using connection ID 'aws_default' for task execution.
[2023-10-18T20:42:54.353-0300] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2023-10-18T20:42:55.269-0300] {lambda_function.py:220} INFO - Lambda response metadata: {'RequestId': 'fea4c335-0950-4088-92c9-0fe51c9f4874', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Wed, 18 Oct 2023 23:42:56 GMT', 'content-type': 'application/json', 'content-length': '234', 'connection': 'keep-alive', 'x-amzn-requestid': 'fea4c335-0950-4088-92c9-0fe51c9f4874', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-65306d80-6dc984374d2e6b1e14ca6e16;sampled=0;lineage=2d7f70ec:0'}, 'RetryAttempts': 0}
[2023-10-18T20:42:55.271-0300] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/amazon/aws/operators/lambda_function.py", line 226, in execute
    raise ValueError(
ValueError: ('Lambda function execution resulted in error', {'ResponseMetadata': {'RequestId': 'fea4c335-0950-4088-92c9-0fe51c9f4874', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Wed, 18 Oct 2023 23:42:56 GMT', 'content-type': 'application/json', 'content-length': '234', 'connection': 'keep-alive', 'x-amzn-requestid': 'fea4c335-0950-4088-92c9-0fe51c9f4874', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-65306d80-6dc984374d2e6b1e14ca6e16;sampled=0;lineage=2d7f70ec:0'}, 'RetryAttempts': 0}, 'Payload': '{"errorMessage": "\'key1\'", "errorType": "KeyError", "requestId": "fea4c335-0950-4088-92c9-0fe51c9f4874", "stackTrace": ["  File \\"/var/task/lambda_function.py\\", line 8, in lambda_handler\\n    print(\\"value1 = \\" + event[\'key1\'])\\n"]}'})
[2023-10-18T20:42:55.292-0300] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=how-desafio-03, task_id=invoke_lambda_function, execution_date=20231018T171000, start_date=20231018T234253, end_date=20231018T234255
[2023-10-18T20:42:55.350-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 50 for task invoke_lambda_function (('Lambda function execution resulted in error', {'ResponseMetadata': {'RequestId': 'fea4c335-0950-4088-92c9-0fe51c9f4874', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Wed, 18 Oct 2023 23:42:56 GMT', 'content-type': 'application/json', 'content-length': '234', 'connection': 'keep-alive', 'x-amzn-requestid': 'fea4c335-0950-4088-92c9-0fe51c9f4874', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-65306d80-6dc984374d2e6b1e14ca6e16;sampled=0;lineage=2d7f70ec:0'}, 'RetryAttempts': 0}, 'Payload': '{"errorMessage": "\'key1\'", "errorType": "KeyError", "requestId": "fea4c335-0950-4088-92c9-0fe51c9f4874", "stackTrace": ["  File \\"/var/task/lambda_function.py\\", line 8, in lambda_handler\\n    print(\\"value1 = \\" + event[\'key1\'])\\n"]}'}); 215)
[2023-10-18T20:42:55.370-0300] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-18T20:42:55.417-0300] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
