[2023-11-06T21:25:46.062-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2023-11-06T09:10:00+00:00/task_id=invoke_lambda_function permission to 509
[2023-11-06T21:25:46.183-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2023-11-06T09:10:00+00:00/task_id=invoke_lambda_function permission to 509
[2023-11-06T21:25:46.250-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2023-11-06T09:10:00+00:00 [queued]>
[2023-11-06T21:25:46.297-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2023-11-06T09:10:00+00:00 [queued]>
[2023-11-06T21:25:46.299-0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-06T21:25:46.402-0300] {taskinstance.py:1382} INFO - Executing <Task(LambdaInvokeFunctionOperator): invoke_lambda_function> on 2023-11-06 09:10:00+00:00
[2023-11-06T21:25:46.405-0300] {standard_task_runner.py:57} INFO - Started process 784 to run task
[2023-11-06T21:25:46.408-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'how-desafio-03', 'invoke_lambda_function', 'scheduled__2023-11-06T09:10:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpbfmwmtuo']
[2023-11-06T21:25:46.409-0300] {standard_task_runner.py:85} INFO - Job 67: Subtask invoke_lambda_function
[2023-11-06T21:25:46.619-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2023-11-06T09:10:00+00:00/task_id=invoke_lambda_function permission to 509
[2023-11-06T21:25:46.625-0300] {task_command.py:416} INFO - Running <TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2023-11-06T09:10:00+00:00 [running]> on host 14111-NB.
[2023-11-06T21:25:46.861-0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='how-desafio-03' AIRFLOW_CTX_TASK_ID='invoke_lambda_function' AIRFLOW_CTX_EXECUTION_DATE='2023-11-06T09:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-06T09:10:00+00:00'
[2023-11-06T21:25:46.862-0300] {lambda_function.py:211} INFO - Invoking AWS Lambda function: my_first_test with payload: {"SampleEvent": {"SampleData": {"Name": "XYZ", "DoB": "1993-01-01"}}}
[2023-11-06T21:25:46.885-0300] {base.py:73} INFO - Using connection ID 'aws_default' for task execution.
[2023-11-06T21:25:46.886-0300] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2023-11-06T21:25:47.965-0300] {lambda_function.py:220} INFO - Lambda response metadata: {'RequestId': '7a3f046d-2599-4d12-b365-1484e41c52da', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Tue, 07 Nov 2023 00:25:50 GMT', 'content-type': 'application/json', 'content-length': '234', 'connection': 'keep-alive', 'x-amzn-requestid': '7a3f046d-2599-4d12-b365-1484e41c52da', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-6549840e-7a3d1861690f183c5d08365c;sampled=0;lineage=2d7f70ec:0'}, 'RetryAttempts': 0}
[2023-11-06T21:25:47.967-0300] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/amazon/aws/operators/lambda_function.py", line 226, in execute
    raise ValueError(
ValueError: ('Lambda function execution resulted in error', {'ResponseMetadata': {'RequestId': '7a3f046d-2599-4d12-b365-1484e41c52da', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Tue, 07 Nov 2023 00:25:50 GMT', 'content-type': 'application/json', 'content-length': '234', 'connection': 'keep-alive', 'x-amzn-requestid': '7a3f046d-2599-4d12-b365-1484e41c52da', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-6549840e-7a3d1861690f183c5d08365c;sampled=0;lineage=2d7f70ec:0'}, 'RetryAttempts': 0}, 'Payload': '{"errorMessage": "\'key1\'", "errorType": "KeyError", "requestId": "7a3f046d-2599-4d12-b365-1484e41c52da", "stackTrace": ["  File \\"/var/task/lambda_function.py\\", line 8, in lambda_handler\\n    print(\\"value1 = \\" + event[\'key1\'])\\n"]}'})
[2023-11-06T21:25:47.987-0300] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=how-desafio-03, task_id=invoke_lambda_function, execution_date=20231106T091000, start_date=20231107T002546, end_date=20231107T002547
[2023-11-06T21:25:48.042-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 67 for task invoke_lambda_function (('Lambda function execution resulted in error', {'ResponseMetadata': {'RequestId': '7a3f046d-2599-4d12-b365-1484e41c52da', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Tue, 07 Nov 2023 00:25:50 GMT', 'content-type': 'application/json', 'content-length': '234', 'connection': 'keep-alive', 'x-amzn-requestid': '7a3f046d-2599-4d12-b365-1484e41c52da', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-6549840e-7a3d1861690f183c5d08365c;sampled=0;lineage=2d7f70ec:0'}, 'RetryAttempts': 0}, 'Payload': '{"errorMessage": "\'key1\'", "errorType": "KeyError", "requestId": "7a3f046d-2599-4d12-b365-1484e41c52da", "stackTrace": ["  File \\"/var/task/lambda_function.py\\", line 8, in lambda_handler\\n    print(\\"value1 = \\" + event[\'key1\'])\\n"]}'}); 784)
[2023-11-06T21:25:48.072-0300] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-06T21:25:48.133-0300] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
