[2023-11-06T21:34:48.254-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=manual__2023-11-07T00:34:43.099800+00:00/task_id=invoke_lambda_function permission to 509
[2023-11-06T21:34:48.431-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=manual__2023-11-07T00:34:43.099800+00:00/task_id=invoke_lambda_function permission to 509
[2023-11-06T21:34:48.538-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: how-desafio-03.invoke_lambda_function manual__2023-11-07T00:34:43.099800+00:00 [queued]>
[2023-11-06T21:34:48.584-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: how-desafio-03.invoke_lambda_function manual__2023-11-07T00:34:43.099800+00:00 [queued]>
[2023-11-06T21:34:48.585-0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-06T21:34:48.690-0300] {taskinstance.py:1382} INFO - Executing <Task(LambdaInvokeFunctionOperator): invoke_lambda_function> on 2023-11-07 00:34:43.099800+00:00
[2023-11-06T21:34:48.693-0300] {standard_task_runner.py:57} INFO - Started process 879 to run task
[2023-11-06T21:34:48.697-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'how-desafio-03', 'invoke_lambda_function', 'manual__2023-11-07T00:34:43.099800+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp5kayt3z2']
[2023-11-06T21:34:48.699-0300] {standard_task_runner.py:85} INFO - Job 82: Subtask invoke_lambda_function
[2023-11-06T21:34:48.978-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=manual__2023-11-07T00:34:43.099800+00:00/task_id=invoke_lambda_function permission to 509
[2023-11-06T21:34:48.985-0300] {task_command.py:416} INFO - Running <TaskInstance: how-desafio-03.invoke_lambda_function manual__2023-11-07T00:34:43.099800+00:00 [running]> on host 14111-NB.
[2023-11-06T21:34:49.366-0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='how-desafio-03' AIRFLOW_CTX_TASK_ID='invoke_lambda_function' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T00:34:43.099800+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-07T00:34:43.099800+00:00'
[2023-11-06T21:34:49.368-0300] {lambda_function.py:211} INFO - Invoking AWS Lambda function: my_first_test with payload: {"weather_daily": {"data": {"date": "2023-11-06 00:00:00+00:00"}}}
[2023-11-06T21:34:49.402-0300] {base.py:73} INFO - Using connection ID 'aws_default' for task execution.
[2023-11-06T21:34:49.403-0300] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2023-11-06T21:34:50.574-0300] {lambda_function.py:220} INFO - Lambda response metadata: {'RequestId': '542da023-c808-4bef-8b56-73219333b009', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Tue, 07 Nov 2023 00:34:52 GMT', 'content-type': 'application/json', 'content-length': '234', 'connection': 'keep-alive', 'x-amzn-requestid': '542da023-c808-4bef-8b56-73219333b009', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-6549862c-5cf004867c1a8ac274a10c78;sampled=0;lineage=2d7f70ec:0'}, 'RetryAttempts': 0}
[2023-11-06T21:34:50.575-0300] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/amazon/aws/operators/lambda_function.py", line 226, in execute
    raise ValueError(
ValueError: ('Lambda function execution resulted in error', {'ResponseMetadata': {'RequestId': '542da023-c808-4bef-8b56-73219333b009', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Tue, 07 Nov 2023 00:34:52 GMT', 'content-type': 'application/json', 'content-length': '234', 'connection': 'keep-alive', 'x-amzn-requestid': '542da023-c808-4bef-8b56-73219333b009', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-6549862c-5cf004867c1a8ac274a10c78;sampled=0;lineage=2d7f70ec:0'}, 'RetryAttempts': 0}, 'Payload': '{"errorMessage": "\'key1\'", "errorType": "KeyError", "requestId": "542da023-c808-4bef-8b56-73219333b009", "stackTrace": ["  File \\"/var/task/lambda_function.py\\", line 8, in lambda_handler\\n    print(\\"value1 = \\" + event[\'key1\'])\\n"]}'})
[2023-11-06T21:34:50.591-0300] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=how-desafio-03, task_id=invoke_lambda_function, execution_date=20231107T003443, start_date=20231107T003448, end_date=20231107T003450
[2023-11-06T21:34:50.701-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 82 for task invoke_lambda_function (('Lambda function execution resulted in error', {'ResponseMetadata': {'RequestId': '542da023-c808-4bef-8b56-73219333b009', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Tue, 07 Nov 2023 00:34:52 GMT', 'content-type': 'application/json', 'content-length': '234', 'connection': 'keep-alive', 'x-amzn-requestid': '542da023-c808-4bef-8b56-73219333b009', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-6549862c-5cf004867c1a8ac274a10c78;sampled=0;lineage=2d7f70ec:0'}, 'RetryAttempts': 0}, 'Payload': '{"errorMessage": "\'key1\'", "errorType": "KeyError", "requestId": "542da023-c808-4bef-8b56-73219333b009", "stackTrace": ["  File \\"/var/task/lambda_function.py\\", line 8, in lambda_handler\\n    print(\\"value1 = \\" + event[\'key1\'])\\n"]}'}); 879)
[2023-11-06T21:34:50.723-0300] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-06T21:34:50.775-0300] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
